note: 'MIND Large'

data_params:
  mind_path: ../data/MINDsmall_train/MINDsmall_train
  batch_size: 16
  seed: 1
  num_workers: 2

module_params:
  lr: 1e-5
  weight_decay: 0.

trainer_params:
  epochs: 3
  precision: 16
  gpus: 1
  strategy: ddp
  val_check_interval: 0.2
  weights_save_path: /usershome/cs671_user8/nrms-bert/experiments
  accumulate_grad_batches: 4
